name: Completionist
options:
  bundleIdPrefix: de.wtimme
targets:
  OSMCompletionist:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    scheme:
      testTargets:
        - OSMCompletionistTests
    sources:
      - Completionist
      - path: src/Shared
      - path: src/iOS
        excludes:
          - "*.xcodeproj"
          - ".gitignore"
          - "Gemfile*"
          - GoMapTests
          - GoMapUITests
          - "Go Map!!-Info.plist"
          - fastlane
          - vendor
          - .bundle
          - "Go Map!!/Images.xcassets"
      - path: src/Images.xcassets
      - path: src/POI-Icons/POI-Icons.xcassets
      - path: src/presets
        buildPhase: resources
        type: folder
    settings:
      base:
        INFOPLIST_FILE: "src/iOS/Go Map!!-Info.plist"
        SWIFT_OBJC_BRIDGING_HEADER: "src/iOS/Go Map!!-Bridging-Header.h"
        GCC_PREFIX_HEADER: "src/iOS/Go Map!!-Prefix.pch"
        SWIFT_OBJC_INTERFACE_HEADER_NAME: "$(SWIFT_MODULE_NAME)-Swift.h"
        PRODUCT_MODULE_NAME: "Go_Map__"
        DEVELOPMENT_TEAM: CH829V2QQB
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: NO
  OSMCompletionistTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "10.0"
    sources:
      - path: src/iOS/GoMapTests
      - path: CompletionistTests
    dependencies:
      - target: OSMCompletionist
  OSMCompletionistUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "10.0"
    scheme:
      testTargets:
        - OSMCompletionistUITests
    sources:
      - path: src/iOS/GoMapUITests
    dependencies:
      - target: OSMCompletionist
