//
// OrgMaprouletteSessionOSMProfile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteSessionOSMProfile: Codable {

    public var _id: Int64
    public var displayName: String
    public var _description: String
    public var avatarURL: String
    public var homeLocation: OrgMaprouletteSessionLocation
    public var created: String

    public init(_id: Int64, displayName: String, _description: String, avatarURL: String, homeLocation: OrgMaprouletteSessionLocation, created: String) {
        self._id = _id
        self.displayName = displayName
        self._description = _description
        self.avatarURL = avatarURL
        self.homeLocation = homeLocation
        self.created = created
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case displayName
        case _description = "description"
        case avatarURL
        case homeLocation
        case created
    }

}

