//
// OrgMaprouletteSessionGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteSessionGroup: Codable {

    public var _id: Int64
    public var name: String
    public var projectId: Int64
    public var groupType: Int
    public var created: String
    public var modified: String

    public init(_id: Int64, name: String, projectId: Int64, groupType: Int, created: String, modified: String) {
        self._id = _id
        self.name = name
        self.projectId = projectId
        self.groupType = groupType
        self.created = created
        self.modified = modified
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case projectId
        case groupType
        case created
        case modified
    }

}

