//
// OrgMaprouletteModelsChallenge.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsChallenge: Codable {

    public var _id: Int64
    public var name: String
    public var created: Int
    public var modified: Int
    public var _description: String?
    public var deleted: Bool
    public var infoLink: String?
    public var general: OrgMaprouletteModelsChallengeGeneral
    public var creation: OrgMaprouletteModelsChallengeCreation
    public var priority: OrgMaprouletteModelsChallengePriority
    public var extra: OrgMaprouletteModelsChallengeExtra
    public var status: Int?
    public var statusMessage: String?
    public var lastTaskRefresh: Int?
    public var dataOriginDate: Int?
    public var location: String?
    public var bounding: String?

    public init(_id: Int64, name: String, created: Int, modified: Int, _description: String?, deleted: Bool, infoLink: String?, general: OrgMaprouletteModelsChallengeGeneral, creation: OrgMaprouletteModelsChallengeCreation, priority: OrgMaprouletteModelsChallengePriority, extra: OrgMaprouletteModelsChallengeExtra, status: Int?, statusMessage: String?, lastTaskRefresh: Int?, dataOriginDate: Int?, location: String?, bounding: String?) {
        self._id = _id
        self.name = name
        self.created = created
        self.modified = modified
        self._description = _description
        self.deleted = deleted
        self.infoLink = infoLink
        self.general = general
        self.creation = creation
        self.priority = priority
        self.extra = extra
        self.status = status
        self.statusMessage = statusMessage
        self.lastTaskRefresh = lastTaskRefresh
        self.dataOriginDate = dataOriginDate
        self.location = location
        self.bounding = bounding
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case created
        case modified
        case _description = "description"
        case deleted
        case infoLink
        case general
        case creation
        case priority
        case extra
        case status
        case statusMessage
        case lastTaskRefresh
        case dataOriginDate
        case location
        case bounding
    }

}

