//
// OrgMaprouletteModelsTaskReviewFields.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsTaskReviewFields: Codable {

    public var reviewStatus: Int?
    public var reviewRequestedBy: Int64?
    public var reviewedBy: Int64?
    public var reviewedAt: String?
    public var reviewStartedAt: String?
    public var reviewClaimedBy: Int64?

    public init(reviewStatus: Int?, reviewRequestedBy: Int64?, reviewedBy: Int64?, reviewedAt: String?, reviewStartedAt: String?, reviewClaimedBy: Int64?) {
        self.reviewStatus = reviewStatus
        self.reviewRequestedBy = reviewRequestedBy
        self.reviewedBy = reviewedBy
        self.reviewedAt = reviewedAt
        self.reviewStartedAt = reviewStartedAt
        self.reviewClaimedBy = reviewClaimedBy
    }


}

