//
// OrgMaprouletteModelsTaskCluster.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsTaskCluster: Codable {

    public var clusterId: Int
    public var numberOfPoints: Int
    public var taskId: Int64?
    public var taskStatus: Int?
    public var taskPriority: Int?
    public var point: OrgMaprouletteModelsPoint
    public var bounding: String
    public var challengeIds: [Int64]
    public var geometries: String?

    public init(clusterId: Int, numberOfPoints: Int, taskId: Int64?, taskStatus: Int?, taskPriority: Int?, point: OrgMaprouletteModelsPoint, bounding: String, challengeIds: [Int64], geometries: String?) {
        self.clusterId = clusterId
        self.numberOfPoints = numberOfPoints
        self.taskId = taskId
        self.taskStatus = taskStatus
        self.taskPriority = taskPriority
        self.point = point
        self.bounding = bounding
        self.challengeIds = challengeIds
        self.geometries = geometries
    }


}

