//
// OrgMaprouletteModelsTaskBundle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsTaskBundle: Codable {

    public var bundleId: Int64
    public var ownerId: Int64
    public var taskIds: [Int64]
    public var tasks: [OrgMaprouletteModelsTask]?

    public init(bundleId: Int64, ownerId: Int64, taskIds: [Int64], tasks: [OrgMaprouletteModelsTask]?) {
        self.bundleId = bundleId
        self.ownerId = ownerId
        self.taskIds = taskIds
        self.tasks = tasks
    }


}

