//
// OrgMaprouletteModelsChallengePriority.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsChallengePriority: Codable {

    public var defaultPriority: Int
    public var highPriorityRule: String?
    public var mediumPriorityRule: String?
    public var lowPriorityRule: String?

    public init(defaultPriority: Int, highPriorityRule: String?, mediumPriorityRule: String?, lowPriorityRule: String?) {
        self.defaultPriority = defaultPriority
        self.highPriorityRule = highPriorityRule
        self.mediumPriorityRule = mediumPriorityRule
        self.lowPriorityRule = lowPriorityRule
    }


}

