//
// OrgMaprouletteModelsTask.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsTask: Codable {

    public var _id: Int64
    public var name: String
    public var created: Int
    public var modified: Int
    public var parent: Int64
    public var instruction: String?
    public var location: String?
    public var geometries: String
    public var suggestedFix: String?
    public var status: Int?
    public var mappedOn: Int?
    public var review: OrgMaprouletteModelsTaskReviewFields
    public var priority: Int
    public var changesetId: Int64?
    public var completionResponses: String?
    public var bundleId: Int64?
    public var isBundlePrimary: Bool?
    public var mapillaryImages: [OrgMaprouletteModelsMapillaryImage]?

    public init(_id: Int64, name: String, created: Int, modified: Int, parent: Int64, instruction: String?, location: String?, geometries: String, suggestedFix: String?, status: Int?, mappedOn: Int?, review: OrgMaprouletteModelsTaskReviewFields, priority: Int, changesetId: Int64?, completionResponses: String?, bundleId: Int64?, isBundlePrimary: Bool?, mapillaryImages: [OrgMaprouletteModelsMapillaryImage]?) {
        self._id = _id
        self.name = name
        self.created = created
        self.modified = modified
        self.parent = parent
        self.instruction = instruction
        self.location = location
        self.geometries = geometries
        self.suggestedFix = suggestedFix
        self.status = status
        self.mappedOn = mappedOn
        self.review = review
        self.priority = priority
        self.changesetId = changesetId
        self.completionResponses = completionResponses
        self.bundleId = bundleId
        self.isBundlePrimary = isBundlePrimary
        self.mapillaryImages = mapillaryImages
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case created
        case modified
        case parent
        case instruction
        case location
        case geometries
        case suggestedFix
        case status
        case mappedOn
        case review
        case priority
        case changesetId
        case completionResponses
        case bundleId
        case isBundlePrimary
        case mapillaryImages
    }

}

