//
// OrgMaprouletteModelsUserNotification.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsUserNotification: Codable {

    public var _id: Int64
    public var userId: Int64
    public var notificationType: Int
    public var created: Int
    public var modified: Int
    public var _description: String?
    public var fromUsername: String?
    public var challengeName: String?
    public var isRead: Bool
    public var emailStatus: Int
    public var taskId: Int64?
    public var challengeId: Int64?
    public var projectId: Int64?
    public var targetId: Int64?
    public var extra: String?

    public init(_id: Int64, userId: Int64, notificationType: Int, created: Int, modified: Int, _description: String?, fromUsername: String?, challengeName: String?, isRead: Bool, emailStatus: Int, taskId: Int64?, challengeId: Int64?, projectId: Int64?, targetId: Int64?, extra: String?) {
        self._id = _id
        self.userId = userId
        self.notificationType = notificationType
        self.created = created
        self.modified = modified
        self._description = _description
        self.fromUsername = fromUsername
        self.challengeName = challengeName
        self.isRead = isRead
        self.emailStatus = emailStatus
        self.taskId = taskId
        self.challengeId = challengeId
        self.projectId = projectId
        self.targetId = targetId
        self.extra = extra
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userId
        case notificationType
        case created
        case modified
        case _description = "description"
        case fromUsername
        case challengeName
        case isRead
        case emailStatus
        case taskId
        case challengeId
        case projectId
        case targetId
        case extra
    }

}

