//
// OrgMaprouletteSessionSearchLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteSessionSearchLocation: Codable {

    public var _left: Double
    public var bottom: Double
    public var _right: Double
    public var top: Double

    public init(_left: Double, bottom: Double, _right: Double, top: Double) {
        self._left = _left
        self.bottom = bottom
        self._right = _right
        self.top = top
    }

    public enum CodingKeys: String, CodingKey { 
        case _left = "left"
        case bottom
        case _right = "right"
        case top
    }

}

