//
// OrgMaprouletteModelsTag.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsTag: Codable {

    public var _id: Int64
    public var name: String
    public var _description: String?
    public var created: String
    public var modified: String
    public var tagType: String

    public init(_id: Int64, name: String, _description: String?, created: String, modified: String, tagType: String) {
        self._id = _id
        self.name = name
        self._description = _description
        self.created = created
        self.modified = modified
        self.tagType = tagType
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _description = "description"
        case created
        case modified
        case tagType
    }

}

