//
// OrgMaprouletteModelsMapillaryImage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsMapillaryImage: Codable {

    public var key: String
    public var lat: Double
    public var lon: Double
    public var url320: String
    public var url640: String
    public var url1024: String
    public var url2048: String

    public init(key: String, lat: Double, lon: Double, url320: String, url640: String, url1024: String, url2048: String) {
        self.key = key
        self.lat = lat
        self.lon = lon
        self.url320 = url320
        self.url640 = url640
        self.url1024 = url1024
        self.url2048 = url2048
    }

    public enum CodingKeys: String, CodingKey { 
        case key
        case lat
        case lon
        case url320 = "url_320"
        case url640 = "url_640"
        case url1024 = "url_1024"
        case url2048 = "url_2048"
    }

}

