//
// OrgMaprouletteSessionTaskPropertySearch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteSessionTaskPropertySearch: Codable {

    public var key: String?
    public var value: String?
    public var valueType: String?
    public var searchType: String?
    public var operationType: String?
    public var _left: OrgMaprouletteSessionTaskPropertySearch?
    public var _right: OrgMaprouletteSessionTaskPropertySearch?

    public init(key: String?, value: String?, valueType: String?, searchType: String?, operationType: String?, _left: OrgMaprouletteSessionTaskPropertySearch?, _right: OrgMaprouletteSessionTaskPropertySearch?) {
        self.key = key
        self.value = value
        self.valueType = valueType
        self.searchType = searchType
        self.operationType = operationType
        self._left = _left
        self._right = _right
    }

    public enum CodingKeys: String, CodingKey { 
        case key
        case value
        case valueType
        case searchType
        case operationType
        case _left = "left"
        case _right = "right"
    }

}

