//
// OrgMaprouletteModelsChallengeCreation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsChallengeCreation: Codable {

    public var overpassQL: String?
    public var remoteGeoJson: String?

    public init(overpassQL: String?, remoteGeoJson: String?) {
        self.overpassQL = overpassQL
        self.remoteGeoJson = remoteGeoJson
    }


}

