//
// OrgMaprouletteModelsPointReview.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsPointReview: Codable {

    public var reviewStatus: Int?
    public var reviewRequestedBy: Int64?
    public var reviewedBy: Int64?
    public var reviewedAt: String?
    public var reviewStartedAt: String?

    public init(reviewStatus: Int?, reviewRequestedBy: Int64?, reviewedBy: Int64?, reviewedAt: String?, reviewStartedAt: String?) {
        self.reviewStatus = reviewStatus
        self.reviewRequestedBy = reviewRequestedBy
        self.reviewedBy = reviewedBy
        self.reviewedAt = reviewedAt
        self.reviewStartedAt = reviewStartedAt
    }


}

