//
// OrgMaprouletteSessionUserSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteSessionUserSettings: Codable {

    public var defaultEditor: Int?
    public var defaultBasemap: Int?
    public var defaultBasemapId: String?
    public var customBasemap: String?
    public var locale: String?
    public var email: String?
    public var emailOptIn: Bool?
    public var leaderboardOptOut: Bool?
    public var needsReview: Int?
    public var isReviewer: Bool?
    public var theme: Int?

    public init(defaultEditor: Int?, defaultBasemap: Int?, defaultBasemapId: String?, customBasemap: String?, locale: String?, email: String?, emailOptIn: Bool?, leaderboardOptOut: Bool?, needsReview: Int?, isReviewer: Bool?, theme: Int?) {
        self.defaultEditor = defaultEditor
        self.defaultBasemap = defaultBasemap
        self.defaultBasemapId = defaultBasemapId
        self.customBasemap = customBasemap
        self.locale = locale
        self.email = email
        self.emailOptIn = emailOptIn
        self.leaderboardOptOut = leaderboardOptOut
        self.needsReview = needsReview
        self.isReviewer = isReviewer
        self.theme = theme
    }


}

