//
// OrgMaprouletteModelsChallengeGeneral.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsChallengeGeneral: Codable {

    public var owner: Int64
    public var parent: Int64
    public var instruction: String
    public var difficulty: Int
    public var blurb: String?
    public var enabled: Bool
    public var challengeType: Int
    public var featured: Bool
    public var hasSuggestedFixes: Bool
    public var popularity: Int?
    public var checkinComment: String
    public var checkinSource: String

    public init(owner: Int64, parent: Int64, instruction: String, difficulty: Int, blurb: String?, enabled: Bool, challengeType: Int, featured: Bool, hasSuggestedFixes: Bool, popularity: Int?, checkinComment: String, checkinSource: String) {
        self.owner = owner
        self.parent = parent
        self.instruction = instruction
        self.difficulty = difficulty
        self.blurb = blurb
        self.enabled = enabled
        self.challengeType = challengeType
        self.featured = featured
        self.hasSuggestedFixes = hasSuggestedFixes
        self.popularity = popularity
        self.checkinComment = checkinComment
        self.checkinSource = checkinSource
    }


}

