//
// OrgMaprouletteSessionLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteSessionLocation: Codable {

    public var latitude: Double
    public var longitude: Double
    public var name: String?

    public init(latitude: Double, longitude: Double, name: String?) {
        self.latitude = latitude
        self.longitude = longitude
        self.name = name
    }


}

