//
// OrgMaprouletteModelsChallengeExtra.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsChallengeExtra: Codable {

    public var defaultZoom: Int
    public var minZoom: Int
    public var maxZoom: Int
    public var defaultBasemap: Int?
    public var defaultBasemapId: String?
    public var customBasemap: String?
    public var updateTasks: Bool
    public var exportableProperties: String?
    public var osmIdProperty: String?
    public var preferredTags: String?
    public var taskStyles: String?

    public init(defaultZoom: Int, minZoom: Int, maxZoom: Int, defaultBasemap: Int?, defaultBasemapId: String?, customBasemap: String?, updateTasks: Bool, exportableProperties: String?, osmIdProperty: String?, preferredTags: String?, taskStyles: String?) {
        self.defaultZoom = defaultZoom
        self.minZoom = minZoom
        self.maxZoom = maxZoom
        self.defaultBasemap = defaultBasemap
        self.defaultBasemapId = defaultBasemapId
        self.customBasemap = customBasemap
        self.updateTasks = updateTasks
        self.exportableProperties = exportableProperties
        self.osmIdProperty = osmIdProperty
        self.preferredTags = preferredTags
        self.taskStyles = taskStyles
    }


}

