//
// OrgMaprouletteModelsVirtualChallenge.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteModelsVirtualChallenge: Codable {

    public var _id: Int64
    public var name: String
    public var created: String
    public var modified: String
    public var _description: String?
    public var ownerId: Int64
    public var expiry: String
    public var taskIdList: [Int64]?

    public init(_id: Int64, name: String, created: String, modified: String, _description: String?, ownerId: Int64, expiry: String, taskIdList: [Int64]?) {
        self._id = _id
        self.name = name
        self.created = created
        self.modified = modified
        self._description = _description
        self.ownerId = ownerId
        self.expiry = expiry
        self.taskIdList = taskIdList
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case created
        case modified
        case _description = "description"
        case ownerId
        case expiry
        case taskIdList
    }

}

