//
// OrgMaprouletteExceptionStatusMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrgMaprouletteExceptionStatusMessage: Codable {

    public var status: String
    public var message: String

    public init(status: String, message: String) {
        self.status = status
        self.message = message
    }


}

