# Disable metrics
opt_out_usage

# Configuration
CHANGELOG_PATH = "./CHANGELOG.md"

default_platform(:ios)

platform :ios do

  desc "Performs basic integration checks to be run before merging"
  lane :pull_request_checks do
    run_tests(
      project: "Go Map!!.xcodeproj",
      scheme: "GoMapTests"
    )
  end

  lane :run_stamp_changelog do
    stamp_changelog(
      changelog_path: './CHANGELOG.md',
      section_identifier: '2.0.0 (42)',
      git_tag: "builds/beta/2.0.0-42",
      stamp_date: "true"
    )
  end

  desc "Uploads a new Beta version to TestFlight"
  lane :beta do
    pull_request_checks

    increment_build_number(
      build_number: get_highest_build_number_from_git_tags() + 1
    )
    commit_version_bump(xcodeproj: "Go Map!!.xcodeproj")

    # Determine the tag (e. g. 'builds/beta/1.6.5-12')
    git_tag = "builds/beta/#{get_version_number()}-#{get_build_number()}"

    # Update the changelog
    section_identifier = "#{get_version_number()} (#{get_build_number()})"
    stamp_changelog(
      changelog_path: CHANGELOG_PATH,
      section_identifier: section_identifier,
      git_tag: git_tag,
      stamp_date: 'true'
    )
    git_commit(
      path: changelog_path,
      message: "Update CHANGELOG.md with changes for #{section_identifier}",
      allow_nothing_to_commit: true
    )

    sync_code_signing(type: "appstore")
    build_app(
      project: "Go Map!!.xcodeproj",
      scheme: "Go Map!!"
    )

    add_git_tag(tag: git_tag)

    push_to_git_remote

    upload_to_testflight
  end

  desc "Re-generates the app icon from the base app_icon.png in the fastlane metadata directory"
  lane :regenerate_app_icon do
    appicon(
      appicon_devices: [:ipad, :iphone, :ios_marketing],
      appicon_path: "Go Map!!/Images.xcassets"
    )
  end

end
