# Disable metrics
opt_out_usage

default_platform(:ios)

platform :ios do

  desc "Performs basic integration checks to be run before merging"
  lane :pull_request_checks do
    run_tests(scheme: "GoMapTests")
  end

  desc "Uploads a new Beta version to TestFlight"
  lane :beta do
    sync_code_signing(type: "appstore")
    build_app(scheme: "Go Map!!")
    upload_to_testflight
  end

end
